
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      APP_ENV: dev
    depends_on:
      - database

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ChangeThisPassword
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: ChangeThisPassword
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  database_data:
