name: Symfony CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      database:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ChangeThisPassword
          MYSQL_DATABASE: app_test
          MYSQL_USER: app
          MYSQL_PASSWORD: ChangeThisPassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer, symfony

      - name: Set environment variables
        run: cp .env.test .env
      
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Install packages
        run: npm install

      - name: Run Encore
        run: npm run build

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit

      - name: Run functional tests
        run: php bin/phpunit --testsuite functional
